[project]
name = "cofferl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "accelerate>=1.7.0",
    "datasets>=3.6.0",
    "gradio>=5.33.0",
    "pandas>=2.3.0",
    "peft>=0.15.2",
    "transformers>=4.52.4",
]
